#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'nodejs',
   :git => 'https://github.com/mdxp/nodejs-cookbook.git'
cookbook 'ruby_build'
cookbook 'rbenv',
  :git => 'https://github.com/fnichol/chef-rbenv',
  :ref => 'v0.7.2'
cookbook 'vim'


