#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'nginx'
cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm'
cookbook 'vim'


