#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'nodejs',
   :git => 'https://github.com/mdxp/nodejs-cookbook.git'
cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm'
cookbook 'vim'


